#pragma once

//PARAMETERS
#define TELEMTRY_DATA_SAMPLES 10
#define TRIPOD_HEIGHT 1.5
#define DEG_TO_KM_RATIO 111
#define STEPS_PER_REVOLUTION 200*6
#define STEPPER_MOTOR_SPEED 50
//PINS
#define BUZZER_PIN 2
#define BUTTION0_PIN 5
#define STEPPER_DRIVER_DIR_PIN 10
#define STEPPER_DRIVER_STEP_PIN 11
#define SERVO_MOTOR_PIN 12