#pragma once

//PARAMETERS
#define TELEMTRY_DATA_SAMPLES 10
#define TRIPOD_HEIGHT 1.5
#define DEG_TO_KM_RATIO 111
#define STEPS_PER_REVOLUTION 200
#define STEPPER_MOTOR_ACCELERATION 50
#define STEPPER_MOTOR_DECELERATION 50
#define STEPPER_MOTOR_MICROSTEPS 4
#define STEPPER_MOTOR_RPM 15
//PINS
#define BUZZER_PIN 16
#define BUTTION0_PIN 14
#define STEPPER_DRIVER_DIR_PIN 2
#define STEPPER_DRIVER_STEP_PIN 0
#define SERVO_MOTOR_PIN 15