#pragma once

//PARAMETERS
#define TELEMTRY_DATA_SAMPLES 2
#define TRIPOD_HEIGHT 2
#define DEG_TO_KM_RATIO 111
#define STEPS_PER_REVOLUTION 200
#define STEPPER_MOTOR_ACCELERATION 50
#define STEPPER_MOTOR_DECELERATION 50
#define STEPPER_MOTOR_MICROSTEPS 16
#define STEPPER_MOTOR_RPM 15
//PINS
#define BUZZER_PIN 13
#define BUTTION0_PIN 7
#define STEPPER_DRIVER_DIR_PIN 8
#define STEPPER_DRIVER_STEP_PIN 9
#define SERVO_MOTOR_PIN 3
//MODES
#define KINEMATICS_DEBUG true